version: '3.8'

services:
  app:
    image: dealautomator:latest
    restart: always
    environment:
      - ENVIRONMENT=production
    deploy:
      replicas: 2
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  worker:
    image: dealautomator:latest
    restart: always
    environment:
      - ENVIRONMENT=production
    deploy:
      replicas: 2
    depends_on:
      - app
      - redis
      - postgres
    command: python -m app.worker

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=dealuser
      - POSTGRES_PASSWORD=dealpass
      - POSTGRES_DB=deals_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
