version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dealuser:dealpass@postgres:5432/deals_db
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - MAX_RETRIES=3
      - WEBHOOK_SECRET=your-webhook-secret
    volumes:
      - .:/app  # for development
    depends_on:
      - postgres
      - redis
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://dealuser:dealpass@postgres:5432/deals_db
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - MAX_RETRIES=3
      - WEBHOOK_SECRET=your-webhook-secret
    depends_on:
      - app
      - redis
      - postgres
    command: python -m app.worker

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=dealuser
      - POSTGRES_PASSWORD=dealpass
      - POSTGRES_DB=deals_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
